DEFAULT_SERVICES = [
    {
        "id": "extensii-1d",
        "name": "Extensii gene 1D",
        "description": "Classic set natural, potrivit pentru prima programare.",
        "duration_min": 180,
        "price_ron": 180,
    },
    {
        "id": "extensii-2d",
        "name": "Extensii gene 2D",
        "description": "Volum fin, usor mai plin decat 1D.",
        "duration_min": 210,
        "price_ron": 210,
    },
    {
        "id": "extensii-3d",
        "name": "Extensii gene 3D",
        "description": "Volum mediu, vizibil si inca purtabil zi de zi.",
        "duration_min": 240,
        "price_ron": 240,
    },
    {
        "id": "extensii-4d",
        "name": "Extensii gene 4D",
        "description": "Volum mai intens, pentru efect glam.",
        "duration_min": 270,
        "price_ron": 270,
    },
    {
        "id": "extensii-5d",
        "name": "Extensii gene 5D",
        "description": "Set dramatic, cu timp generos pentru lucru atent.",
        "duration_min": 300,
        "price_ron": 300,
    },
    {
        "id": "extensii-6d-plus",
        "name": "Extensii gene 6D+",
        "description": "Mega volum, potrivit pentru cliente care vor impact maxim.",
        "duration_min": 360,
        "price_ron": 340,
    },
    {
        "id": "intretinere-1d",
        "name": "Intretinere 1D",
        "description": "Refill pentru set 1D, recomandat la 2-3 saptamani.",
        "duration_min": 120,
        "price_ron": 120,
    },
    {
        "id": "intretinere-2d",
        "name": "Intretinere 2D",
        "description": "Refill fin pentru volum 2D, cu curatare si completare.",
        "duration_min": 135,
        "price_ron": 140,
    },
    {
        "id": "intretinere-3d",
        "name": "Intretinere 3D",
        "description": "Reimprospatare volum mediu pentru gene uniforme.",
        "duration_min": 150,
        "price_ron": 160,
    },
    {
        "id": "intretinere-4d",
        "name": "Intretinere 4D",
        "description": "Refill pentru volum intens, cu timp extra pentru aranjare.",
        "duration_min": 165,
        "price_ron": 180,
    },
    {
        "id": "intretinere-5d",
        "name": "Intretinere 5D",
        "description": "Intretinere dramatica, pentru pastrarea efectului plin.",
        "duration_min": 180,
        "price_ron": 200,
    },
    {
        "id": "intretinere-6d-plus",
        "name": "Intretinere 6D+",
        "description": "Refill mega volum, cu timp generos pentru simetrie.",
        "duration_min": 210,
        "price_ron": 230,
    },
    {
        "id": "demontare-gene",
        "name": "Demontare gene",
        "description": "Demontare blanda si curatare, fara smuls sau tras de genele naturale.",
        "duration_min": 45,
        "price_ron": 60,
    },
]
